[tasks.zigbuild]
command = "cargo-zigbuild"
args = ["build", "--release"]

# [tasks.compress]
# script = '''
# upx --best --lzma target/release/meyrin
# '''

[tasks.normal]
command = "cargo"
args = ["build", "--release"]

[tasks.optimize]
dependencies = ["zigbuild"]

[tasks.build]
dependencies = ["normal"]